pub fn source(binding: &str, spoof: bool) -> String {
    SRC.replacen("__B__", binding, 1)
        .replacen("__G__", if spoof { "1" } else { "0" }, 1)
}

const SRC: &str = r#"(function(){
"use strict";
var B="__B__",L=[],CAP=6000,DR=0,LN=0,SN=0,EVN=0,FNN=0,PON=0,WEN=0,WMDD=0,MQN=0,WSN=0,SLN=0,AG=Object.create(null),MS=Object.create(null),MM=Object.create(null),SLC=Object.create(null),ARM=Object.create(null),STK=Object.create(null),SRCN=Object.create(null),WMR=[];
var TS=Function.prototype.toString,OWN=TS.call(TS),SYM=Symbol.for("afx"+B),SH=null;
try{if(window.parent&&window.parent!==window)SH=window.parent[SYM]}catch(x){}
var WK=SH?SH.w:new WeakMap();
function P(f,s){WK.set(f,s);return f}
try{Function.prototype.toString=P(function toString(){var s=WK.get(this);return s===void 0?TS.call(this):s},OWN)}catch(x){}
try{Object.defineProperty(window,SYM,{value:{w:WK},writable:false,enumerable:false,configurable:false})}catch(x){}
function T(){return performance.now()}
function W(k,v){if(L.length>CAP){DR++;return}L.push(k,v,T())}
function C(n){AG[n]=(AG[n]||0)+1}
function M(n,d){MS[n]=(MS[n]||0)+d;var e=MM[n];if(e===void 0||d>e)MM[n]=d;if(d>8){var c=SLC[n]||0;if(c<5&&SLN<800){SLC[n]=c+1;SLN++;W("slow:"+n,[Math.round(d*100)/100,T()])}}}
function A(a){var r=[],i,v;for(i=0;i<a.length&&i<6;i++){v=a[i];r.push(typeof v==="number"?Math.round(v*100)/100:typeof v==="string"?v.slice(0,80):v instanceof ArrayBuffer?v.byteLength:v&&v.byteLength?v.byteLength:v&&v.length?String(v.length):0)}return r}
function BDY(b){try{if(b===null||b===void 0)return 0;if(typeof b==="string")return b.slice(0,512);if(typeof b==="number")return b;if(b instanceof URLSearchParams)return String(b).slice(0,512);if(typeof b.append==="function"){var s="";b.forEach(function(v,k){if(s.length<512)s+=k+"="+String(v).slice(0,64)+"&"});return s}return b.byteLength?b.byteLength:0}catch(x){return 0}}
function ST(tag){var n=STK[tag]||0;if(n>=3)return;STK[tag]=n+1;try{W("stk:"+tag,[String(new Error().stack||"").slice(0,600),T()])}catch(x){}}
function CB(cb,tag){var n=SRCN[tag]||0,src="";try{src=TS.call(cb)}catch(x){}if(n<3){SRCN[tag]=n+1;if(src)W("src:"+tag,[src.slice(0,4000),T()])}return P(function(){var t0=T();try{return Reflect.apply(cb,this,arguments)}finally{M(tag,T()-t0);C(tag)}},src||OWN)}
var TN=Object.create(null),TNC=0,TDEL=[],TMAX=8192,DEL=new Uint8Array(128),DLM=" \"',:;=&{}[]()<>?/\\+|*#%";
try{for(var di=0;di<DLM.length;di++)DEL[DLM.charCodeAt(di)]=1}catch(x){}
function FNV(s){var h=0x811c9dc5,i,c;for(i=0;i<s.length;i++){c=s.charCodeAt(i);h^=c;h=Math.imul(h,16777619)>>>0}return h>>>0}
function TAS(h){if(TN[h])return;if(TNC>=TMAX){for(var k in TN){delete TN[k];TNC--;break}}TN[h]=1;TNC++;if(TDEL.length<256)TDEL.push(h)}
function TT(s){if(typeof s!=="string"||s.length<3)return;var i,c,h=0x811c9dc5,run=0,lim=s.length>1024?1024:s.length;if(lim>=3)TAS(FNV(s.slice(0,1024)));for(i=0;i<=lim;i++){c=i<lim?s.charCodeAt(i):32;if(c>32&&c<127&&DEL[c]!==1){h^=c;h=Math.imul(h,16777619)>>>0;run++}else{if(run>=3)TAS(h);h=0x811c9dc5;run=0}}}
function TTv(v){try{if(typeof v==="string")TT(v);else if(typeof v==="number"&&v>0&&v<1e9&&v%1===0)TT(String(v))}catch(x){}}
function TCT(s){if(typeof s!=="string"||!s.length)return 0;var i,c,h=0x811c9dc5,run=0,n=0,lim=s.length>4096?4096:s.length;for(i=0;i<=lim;i++){c=i<lim?s.charCodeAt(i):32;if(c>32&&c<127&&DEL[c]!==1){h^=c;h=Math.imul(h,16777619)>>>0;run++}else{if(run>=3&&TN[h])n++;h=0x811c9dc5;run=0}}return n}
function FNV8(u){var h=0x811c9dc5,i;for(i=0;i<u.length;i++){h^=u[i];h=Math.imul(h,16777619)>>>0}return h>>>0}
function B64(u){var s="",i;for(i=0;i<u.length;i+=512)s+=String.fromCharCode.apply(null,u.subarray(i,i+512));try{return btoa(s)}catch(x){return ""}}
function WMD(){if(WMDD>=3)return 0;var out=[],i,m,b,u;for(i=0;i<WMR.length;i++){try{m=WMR[i].deref();if(!m){WMR.splice(i,1);i--;continue}b=m.buffer;if(!b)continue;u=new Uint8Array(b,0,Math.min(2048,b.byteLength));out.push([b.byteLength,FNV8(new Uint8Array(b,0,Math.min(4096,b.byteLength))),B64(u)])}catch(x){}}if(out.length)WMDD++;return out.length?out:0}
function FL(){var a=[],m=[],x=[],k;for(k in AG){a.push(k,AG[k])}for(k in MS){m.push(k,MS[k])}for(k in MM){x.push(k,Math.round(MM[k]*100)/100)}AG=Object.create(null);MS=Object.create(null);MM=Object.create(null);if(a.length)W("_c",a);if(m.length)W("_m",m);if(x.length)W("_mm",x);if(DR){W("_dr",DR);DR=0}if(TDEL.length){W("_th",TDEL);TDEL=[]}var p=null;if(L.length){try{p=JSON.stringify(L)}catch(x2){L.length=0}}if(p!==null){try{window[B]&&window[B](p)}catch(x3){}}L.length=0}
setInterval(FL,700);
addEventListener("pagehide",FL);
function GP(o,p){try{var d=Object.getOwnPropertyDescriptor(o,p);if(!d||!d.get){return}Object.defineProperty(o,p,{get:P(new Proxy(d.get,{apply:function(t,h,a){var r=Reflect.apply(t,h,a);C("g:"+p);TTv(r);ST("g:"+p);return r}}),TS.call(d.get)),set:d.set,configurable:d.configurable,enumerable:d.enumerable})}catch(x){}}
function GC(o,p){try{var d=Object.getOwnPropertyDescriptor(o,p);if(!d||typeof d.value!=="function"){return}var n=d.value;Object.defineProperty(o,p,{value:P(new Proxy(n,{apply:function(t,h,a){C(p);ST(p);return Reflect.apply(t,h,a)}}),TS.call(n)),writable:d.writable,configurable:d.configurable,enumerable:d.enumerable})}catch(x){}}
function FP(o,p,cap){try{var d=Object.getOwnPropertyDescriptor(o,p);if(!d||typeof d.value!=="function"){return}var n=d.value,ct=0;Object.defineProperty(o,p,{value:P(new Proxy(n,{apply:function(t,h,a){if(ct<(cap||120)){ct++;W(p,[A(a),T()]);TTv(a&&a[0]);return Reflect.apply(t,h,a)}C(p);return Reflect.apply(t,h,a)}}),TS.call(n)),writable:d.writable,configurable:d.configurable,enumerable:d.enumerable})}catch(x){}}
function FT(o,p){try{var d=Object.getOwnPropertyDescriptor(o,p);if(!d||typeof d.value!=="function"){return}var n=d.value;Object.defineProperty(o,p,{value:P(new Proxy(n,{apply:function(t,h,a){var t0=T(),r=Reflect.apply(t,h,a);M(p,T()-t0);C(p);TTv(r);ST(p);return r}}),TS.call(n)),writable:d.writable,configurable:d.configurable,enumerable:d.enumerable})}catch(x){}}
function SGP(o,p){try{var d=Object.getOwnPropertyDescriptor(o,p);if(!d||typeof d.value!=="function"){return}var n=d.value,sp="__G__"==="1";Object.defineProperty(o,p,{value:P(new Proxy(n,{apply:function(t,h,a){var t0=T(),r=Reflect.apply(t,h,a),k=a&&a[0];if(sp&&k===37445){r="Google Inc. (Intel)"}else if(sp&&k===37446){r="ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E92) (0x00008086) Vulkan 1.3.283 (0x040041C5), Vulkan)"}M(p,T()-t0);C(p);TTv(r);ST(p);return r}}),TS.call(n)),writable:d.writable,configurable:d.configurable,enumerable:d.enumerable})}catch(x){}}
function GS(o){try{var d=Object.getOwnPropertyDescriptor(o,"shaderSource");if(!d||typeof d.value!=="function"){return}var n=d.value,ct=0;Object.defineProperty(o,"shaderSource",{value:P(new Proxy(n,{apply:function(t,h,a){C("shaderSource");if(ct<10){ct++;W("gl:shader",[(a&&typeof a[1]==="string")?a[1].slice(0,1024):"",T()])}return Reflect.apply(t,h,a)}}),TS.call(n)),writable:d.writable,configurable:d.configurable,enumerable:d.enumerable})}catch(x){}}
function WC(n){try{var o=window[n];if(typeof o!=="function"){return}Object.defineProperty(window,n,{value:P(new Proxy(o,{construct:function(t,a){if(n==="PerformanceObserver"&&a&&typeof a[0]==="function"){try{a[0]=CB(a[0],"po:cb")}catch(x){}}if(n==="Worker"&&a&&typeof a[0]==="string"&&(a[0].indexOf("blob:")===0||a[0].indexOf("data:")===0)&&WSN<20){WSN++;try{fetch(a[0]).then(function(r){return r.text()}).then(function(s){W("worker:src",[String(s.length),s.slice(0,4096),T()])}).catch(function(){})}catch(x){}}W("new:"+n,[A(a),T()]);return Reflect.construct(t,a)},apply:function(t,h,a){W("call:"+n,[A(a),T()]);return Reflect.apply(t,h,a)}}),TS.call(o)),writable:true,configurable:true,enumerable:true})}catch(x){}
if(n==="PerformanceObserver"){try{var POB0=Object.getOwnPropertyDescriptor(o.prototype,"observe");if(POB0&&typeof POB0.value==="function"){Object.defineProperty(o.prototype,"observe",{value:P(new Proxy(POB0.value,{apply:function(t,h,a){try{var q=a&&a[0],et=q&&q.entryTypes?String(q.entryTypes.join("|")).slice(0,120):((q&&q.type)?String(q.type):"");if(PON<40){PON++;W("po:obs",[et,T()])}else{C("po:obs")}}catch(x){}return Reflect.apply(t,h,a)}}),TS.call(POB0.value)),writable:true,configurable:true,enumerable:true});GC(o.prototype,"disconnect");GC(o.prototype,"takeRecords")}}catch(x){}}}
try{var NP=window.Navigator&&Navigator.prototype;
if(NP){["webdriver","plugins","mimeTypes","languages","hardwareConcurrency","deviceMemory","platform","vendor","userAgent","doNotTrack","maxTouchPoints","cookieEnabled","onLine","connection","pdfViewerEnabled","globalPrivacyControl","mediaDevices","storage","credentials","geolocation","permissions"].forEach(function(p){GP(NP,p)});
["getBattery","vibrate","getGamepads","requestMIDIAccess","share"].forEach(function(p){GC(NP,p)})}}catch(x){}
try{if(window.Screen&&Screen.prototype){["width","height","availWidth","availHeight","colorDepth","pixelDepth","availLeft","availTop"].forEach(function(p){GP(Screen.prototype,p)})}}catch(x){}
try{if(window.HTMLCanvasElement&&HTMLCanvasElement.prototype){FT(HTMLCanvasElement.prototype,"toDataURL");FT(HTMLCanvasElement.prototype,"toBlob");FP(HTMLCanvasElement.prototype,"getContext",80);GC(HTMLCanvasElement.prototype,"transferControlToOffscreen")}var CP=window.CanvasRenderingContext2D&&CanvasRenderingContext2D.prototype;
if(CP){FT(CP,"getImageData")}var OP=window.OffscreenCanvasRenderingContext2D&&OffscreenCanvasRenderingContext2D.prototype;
if(OP){FT(OP,"getImageData")}var OC=window.OffscreenCanvas&&OffscreenCanvas.prototype;
if(OC){FT(OC,"convertToBlob");FP(OC,"getContext",80);GC(OC,"transferToImageBitmap")}}catch(x){}
try{if(window.WebGLRenderingContext&&WebGLRenderingContext.prototype){SGP(WebGLRenderingContext.prototype,"getParameter");["getExtension","getSupportedExtensions","getShaderPrecisionFormat","getAttachedShaders","getProgramInfoLog"].forEach(function(p){FT(WebGLRenderingContext.prototype,p)});GS(WebGLRenderingContext.prototype)}if(window.WebGL2RenderingContext&&WebGL2RenderingContext.prototype){SGP(WebGL2RenderingContext.prototype,"getParameter");["getExtension"].forEach(function(p){FT(WebGL2RenderingContext.prototype,p)});GS(WebGL2RenderingContext.prototype)}}catch(x){}
try{if(window.AnalyserNode&&AnalyserNode.prototype){FT(AnalyserNode.prototype,"getFloatFrequencyData")}if(window.OfflineAudioContext&&OfflineAudioContext.prototype){FT(OfflineAudioContext.prototype,"startRendering")}}catch(x){}
try{if(window.Storage&&Storage.prototype){["getItem","setItem","removeItem","clear","key"].forEach(function(p){GC(Storage.prototype,p)})}}catch(x){}
try{var CD=Object.getOwnPropertyDescriptor(Document.prototype,"cookie");
if(CD&&CD.get){Object.defineProperty(Document.prototype,"cookie",{get:P(new Proxy(CD.get,{apply:function(t,h,a){C("cookie:get");return Reflect.apply(t,h,a)}}),TS.call(CD.get)),set:CD.set?P(new Proxy(CD.set,{apply:function(t,h,a){C("cookie:set");return Reflect.apply(t,h,a)}}),TS.call(CD.set)):CD.set,configurable:true,enumerable:true})}}catch(x){}
try{var NF=window.fetch;if(typeof NF==="function"){Object.defineProperty(window,"fetch",{value:P(new Proxy(NF,{apply:function(t,h,a){var t0=T(),o=(a&&a[1])||{},u=a&&a[0],us=(typeof u==="string")?u:((u&&u.url)?u.url:""),bs=BDY(o&&o.body),tn=TCT(typeof bs==="string"?bs:"")+TCT(us),pr=Reflect.apply(t,h,a);if(pr&&typeof pr.then==="function"){pr.then(function(){M("fetch",T()-t0);C("fetch")},function(){})}W("net:send",[us.slice(0,300),(o&&o.method)||"GET",bs,T(),tn,WMD()]);return pr}}),TS.call(NF)),writable:true,configurable:true,enumerable:true})}}catch(x){}
try{if(window.XMLHttpRequest&&XMLHttpRequest.prototype){var XO=XMLHttpRequest.prototype.open,XS=XMLHttpRequest.prototype.send,NAE=(window.EventTarget&&EventTarget.prototype)?EventTarget.prototype.addEventListener:null;XMLHttpRequest.prototype.open=P(new Proxy(XO,{apply:function(t,h,a){try{Object.defineProperty(h,"__afm",{value:(a&&a[0])||"GET",writable:true,enumerable:false,configurable:true});Object.defineProperty(h,"__afu",{value:(a&&a[1])?String(a[1]).slice(0,300):"",writable:true,enumerable:false,configurable:true})}catch(x){}return Reflect.apply(t,h,a)}}),TS.call(XO));XMLHttpRequest.prototype.send=P(new Proxy(XS,{apply:function(t,h,a){var t0=T(),bs=BDY(a&&a[0]),uu=(h&&h.__afu)||"",tn=TCT(typeof bs==="string"?bs:"")+TCT(uu);try{if(NAE)Reflect.apply(NAE,h,["loadend",function(){M("xhr",T()-t0)}])}catch(x){}W("net:send",[uu,(h&&h.__afm)||"GET",bs,T(),tn,WMD()]);return Reflect.apply(t,h,a)}}),TS.call(XS))}}catch(x){}
try{if(window.Navigator&&Navigator.prototype&&Navigator.prototype.sendBeacon){var SB=Navigator.prototype.sendBeacon;Object.defineProperty(Navigator.prototype,"sendBeacon",{value:P(new Proxy(SB,{apply:function(t,h,a){var bs=BDY(a&&a[1]),uu=(a&&a[0])?String(a[0]).slice(0,300):"";W("net:send",[uu,"BEACON",bs,T(),TCT(typeof bs==="string"?bs:"")+TCT(uu),WMD()]);return Reflect.apply(t,h,a)}}),TS.call(SB)),writable:true,configurable:true,enumerable:true})}}catch(x){}
try{if(window.SharedArrayBuffer){var SABC=SharedArrayBuffer;Object.defineProperty(window,"SharedArrayBuffer",{value:P(new Proxy(SABC,{construct:function(t,a){W("sab",[a&&a[0]||0,T()]);return Reflect.construct(t,a)}}),TS.call(SABC)),writable:true,configurable:true,enumerable:true});if(SABC.prototype){GC(SABC.prototype,"grow")}}}catch(x){}
try{if(window.Atomics){["store","load","add","sub","and","or","xor","exchange","compareExchange","wait","notify","waitAsync"].forEach(function(p){GC(Atomics,p)})}}catch(x){}
try{if(window.Performance&&Performance.prototype){["getEntries","getEntriesByType","getEntriesByName","mark","measure"].forEach(function(p){GC(Performance.prototype,p)})}}catch(x){}
var WA="mousemove mouseup mousedown click dblclick keydown keyup keypress wheel scroll touchstart touchmove touchend pointerdown pointermove pointerup input change focus blur copy paste contextmenu visibilitychange resize".split(" ");
try{if(window.EventTarget&&EventTarget.prototype){var AE=EventTarget.prototype.addEventListener,RE=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=P(new Proxy(AE,{apply:function(t,h,a){var ty=a&&a[0];if(typeof ty==="string"){C("listen:"+ty);if(LN<200){LN++;W("listen",[ty,(h&&h.tagName)||((h===window)?"window":((h===document)?"document":"*")),(a&&a[2])?1:0,T()])}if(WA.indexOf(ty)>=0&&!ARM[ty]){ARM[ty]=1;try{Reflect.apply(AE,window,[ty,P(function(){C("disp:"+ty)},OWN),true])}catch(x){}}}return Reflect.apply(t,h,a)}}),TS.call(AE));EventTarget.prototype.removeEventListener=P(new Proxy(RE,{apply:function(t,h,a){if(a&&typeof a[0]==="string"){C("rm:"+a[0])}return Reflect.apply(t,h,a)}}),TS.call(RE));GC(EventTarget.prototype,"dispatchEvent")}}catch(x){}
try{var RAF=window.requestAnimationFrame;if(typeof RAF==="function"){Object.defineProperty(window,"requestAnimationFrame",{value:P(new Proxy(RAF,{apply:function(t,h,a){C("rAF");if(a&&typeof a[0]==="function"){a[0]=CB(a[0],"raf:cb")}return Reflect.apply(t,h,a)}}),TS.call(RAF)),writable:true,configurable:true,enumerable:true})}}catch(x){}
try{var STO=window.setTimeout,SIO=window.setInterval;Object.defineProperty(window,"setTimeout",{value:P(new Proxy(STO,{apply:function(t,h,a){C("setTimeout");if(a&&typeof a[0]==="function"){a[0]=CB(a[0],"tmr:cb")}return Reflect.apply(t,h,a)}}),TS.call(STO)),writable:true,configurable:true,enumerable:true});Object.defineProperty(window,"setInterval",{value:P(new Proxy(SIO,{apply:function(t,h,a){C("setInterval");if(a&&typeof a[0]==="function"){a[0]=CB(a[0],"ivl:cb")}return Reflect.apply(t,h,a)}}),TS.call(SIO)),writable:true,configurable:true,enumerable:true})}catch(x){}
try{if(window.Performance&&Performance.prototype){var PN=Object.getOwnPropertyDescriptor(Performance.prototype,"now");if(PN&&PN.get){Performance.prototype.now=P(new Proxy(PN.get,{apply:function(t,h,a){C("performance.now");return Reflect.apply(t,h,a)}}),TS.call(PN.get))}}}catch(x){}
try{var DN=Object.getOwnPropertyDescriptor(Date,"now");if(DN&&DN.value){Object.defineProperty(Date,"now",{value:P(new Proxy(DN.value,{apply:function(t,h,a){C("Date.now");return Reflect.apply(t,h,a)}}),TS.call(DN.value)),writable:true,configurable:false})}}catch(x){}
try{var MR=Math.random;Math.random=P(new Proxy(MR,{apply:function(t,h,a){var r=Reflect.apply(t,h,a);C("Math.random");TT(String(r));return r}}),TS.call(MR))}catch(x){}
try{var EV=window.eval;if(typeof EV==="function"){Object.defineProperty(window,"eval",{value:P(new Proxy(EV,{apply:function(t,h,a){if(EVN<40){EVN++;W("call:eval",[A(a),T()])}else{C("call:eval")}ST("call:eval");return Reflect.apply(t,h,a)}}),TS.call(EV)),writable:true,configurable:true,enumerable:false})}}catch(x){}
try{var FN=window.Function;if(typeof FN==="function"){Object.defineProperty(window,"Function",{value:P(new Proxy(FN,{construct:function(t,a){if(FNN<40){FNN++;W("new:Function",[a?a.map(function(x){return String(x).slice(0,96)}):0,T()])}else{C("new:Function")}ST("new:Function");return Reflect.construct(t,a)},apply:function(t,h,a){if(FNN<40){FNN++;W("call:Function",[a?a.map(function(x){return String(x).slice(0,96)}):0,T()])}else{C("call:Function")}ST("call:Function");return Reflect.apply(t,h,a)}}),TS.call(FN)),writable:true,configurable:true,enumerable:false})}}catch(x){}
try{if(window.WebAssembly){["instantiate","compile","instantiateStreaming","compileStreaming","validate"].forEach(function(p){try{var d=Object.getOwnPropertyDescriptor(WebAssembly,p);if(!d||typeof d.value!=="function"){return}var n=d.value;Object.defineProperty(WebAssembly,p,{value:P(new Proxy(n,{apply:function(t,h,a){var b=a&&a[0],sz=b?(b.byteLength||b.length||0):0,t0=T(),r=Reflect.apply(t,h,a);M("wasm:"+p,T()-t0);C("wasm:"+p);if(sz){W("wasm",[sz,T()])}if((p==="instantiate"||p==="instantiateStreaming")&&r&&typeof r.then==="function"){r.then(function(res){try{var ex=res&&res.instance?res.instance.exports:(res?res.exports:null);if(ex&&WEN<40){WEN++;W("wasm:exp",[Object.keys(ex).slice(0,40).join(",").slice(0,300),T()])}}catch(x){}},function(){})}return r}}),TS.call(n)),writable:true,configurable:true,enumerable:true})}catch(x){}});var WMC=WebAssembly.Memory;if(WMC){try{Object.defineProperty(WebAssembly,"Memory",{value:P(new Proxy(WMC,{construct:function(t,a){var o=(a&&a[0])||{},r=Reflect.construct(t,a);try{if(WMR.length<8)WMR.push(new WeakRef(r));W("wmem:new",[o.initial||0,o.max||0,T()])}catch(x){}return r}}),TS.call(WMC)),writable:true,configurable:true,enumerable:true})}catch(x){}}try{var WGP=WebAssembly.Memory.prototype&&Object.getOwnPropertyDescriptor(WebAssembly.Memory.prototype,"grow");if(WGP&&typeof WGP.value==="function"){Object.defineProperty(WebAssembly.Memory.prototype,"grow",{value:P(new Proxy(WGP.value,{apply:function(t,h,a){var r=Reflect.apply(t,h,a);try{W("wmem:grow",[(a&&a[0])||0,((r&&r.buffer&&r.buffer.byteLength)||((r&&r.byteLength)||0)),T()])}catch(x){}return r}}),TS.call(WGP.value)),writable:true,configurable:true,enumerable:true})}}catch(x){}}}catch(x){}
try{if(window.FontFaceSet&&FontFaceSet.prototype){GC(FontFaceSet.prototype,"check")}if(window.Intl&&Intl.DateTimeFormat&&Intl.DateTimeFormat.prototype){GC(Intl.DateTimeFormat.prototype,"resolvedOptions")}if(window.Geolocation&&Geolocation.prototype){GC(Geolocation.prototype,"getCurrentPosition");GC(Geolocation.prototype,"watchPosition")}if(window.Permissions&&Permissions.prototype){GC(Permissions.prototype,"query")}if(window.MediaDevices&&MediaDevices.prototype){GC(MediaDevices.prototype,"enumerateDevices")}if(window.StorageManager&&StorageManager.prototype){GC(StorageManager.prototype,"estimate")}if(window.CredentialsContainer&&CredentialsContainer.prototype){GC(CredentialsContainer.prototype,"get");GC(CredentialsContainer.prototype,"create")}if(window.History&&History.prototype){GC(History.prototype,"pushState");GC(History.prototype,"replaceState")}if(window.SubtleCrypto&&SubtleCrypto.prototype&&window.crypto&&window.crypto.subtle){GC(SubtleCrypto.prototype,"digest")}if(window.SpeechSynthesis&&SpeechSynthesis.prototype){GC(SpeechSynthesis.prototype,"getVoices")}if(window.ServiceWorkerContainer&&ServiceWorkerContainer.prototype){GC(ServiceWorkerContainer.prototype,"register")}if(window.Clipboard&&Clipboard.prototype){GC(Clipboard.prototype,"readText");GC(Clipboard.prototype,"writeText")}if(window.RTCPeerConnection&&RTCPeerConnection.prototype){GC(RTCPeerConnection.prototype,"createOffer");GC(RTCPeerConnection.prototype,"createDataChannel")}if(window.Window&&Window.prototype){GC(Window.prototype,"postMessage")}if(window.Document&&Document.prototype){GP(Document.prototype,"visibilityState");GP(Document.prototype,"hidden")}}catch(x){}
try{["AudioContext","OfflineAudioContext","Worker","SharedWorker","WebSocket","RTCPeerConnection","Notification","EventSource","OffscreenCanvas","PerformanceObserver"].forEach(function(n){WC(n)})}catch(x){}
try{if(window.Element&&Element.prototype){var SA=Object.getOwnPropertyDescriptor(Element.prototype,"setAttribute");
if(SA){Object.defineProperty(Element.prototype,"setAttribute",{value:P(new Proxy(SA.value,{apply:function(t,h,a){var n=(a&&a[0])?String(a[0]):"";if(n==="src"||n==="srcdoc"||n==="data"){if(SN<200){SN++;W("setattr:"+n,[(a&&a[1])?String(a[1]).slice(0,160):"",T()])}else{C("setattr")}}else{C("setattr")}return Reflect.apply(t,h,a)}}),TS.call(SA.value)),writable:true,configurable:true,enumerable:true})}GC(Element.prototype,"getBoundingClientRect")}if(window.HTMLElement&&HTMLElement.prototype){["offsetWidth","offsetHeight","offsetLeft","offsetTop","clientWidth","clientHeight"].forEach(function(p){GC(HTMLElement.prototype,p)})}}catch(x){}
try{var CS=Object.getOwnPropertyDescriptor(window,"getComputedStyle");if(CS&&CS.value){Object.defineProperty(window,"getComputedStyle",{value:P(new Proxy(CS.value,{apply:function(t,h,a){C("getComputedStyle");return Reflect.apply(t,h,a)}}),TS.call(CS.value)),writable:true,configurable:true,enumerable:true})}}catch(x){}
try{var MQ=window.matchMedia;if(typeof MQ==="function"){Object.defineProperty(window,"matchMedia",{value:P(new Proxy(MQ,{apply:function(t,h,a){var q=a&&a[0];C("matchMedia");if(MQN<30&&typeof q==="string"){MQN++;W("mq:query",[q.slice(0,120),T()])}return Reflect.apply(t,h,a)}}),TS.call(MQ)),writable:true,configurable:true,enumerable:true})}}catch(x){}
try{var IF=Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype,"src");
if(IF){Object.defineProperty(HTMLIFrameElement.prototype,"src",{get:IF.get?P(new Proxy(IF.get,{apply:function(t,h,a){C("iframe.src:get");return Reflect.apply(t,h,a)}}),TS.call(IF.get)):undefined,set:IF.set?P(new Proxy(IF.set,{apply:function(t,h,a){C("iframe.src:set");return Reflect.apply(t,h,a)}}),TS.call(IF.set)):undefined,configurable:true,enumerable:true})}}catch(x){}
try{GP(window,"localStorage");GP(window,"sessionStorage");GP(window,"indexedDB")}catch(x){}
W("_boot",[navigator.userAgent.slice(0,160),String(location.href).slice(0,200),T(),SH?1:0,"__G__"==="1"?1:0]);
})()"#;
